spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: todo
    password: todo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace