version: '3'
services:
  todo-back:
    build: .
    image: todo-back:dev
    container_name: todo-back
    command: "mvn package && java -jar target/todo.jar"
    volumes:
      - .:/todo-back
    ports:
      - 8080:8080
    depends_on:
      - postgresJPA
  postgresJPA:
    image: postgis/postgis:14-3.2-alpine
    volumes:
      - .dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo
    ports:
      - 5432:5432